import 'dart:ui';


import 'package:easy_localization/easy_localization.dart';

import 'localization_key.dart';

class LocalizationLoader extends AssetLoader {
 const LocalizationLoader();

 @override
 Future<Map<String, dynamic>> load(String path, Locale locale) async {
  if (locale.languageCode == 'en') {
   return {
    TranslationKey.onBoardingText1: "A wide range of heavy and light equipment for all types of projects",
    TranslationKey.onBoardingText2: "Smart booking and fast, direct delivery to the job site with a click of a button",
    TranslationKey.onBoardingText3: "Guaranteed equipment, regular maintenance, and integrated technical support to ensure your success",
    TranslationKey.onBoardingTitle1: "Your equipment.. in your pocket",
    TranslationKey.onBoardingTitle2: "Order it.. it delivers to your location",
    TranslationKey.onBoardingTitle3: "Start your construction.. with confidence",
    TranslationKey.goBack: "Go Back",
    TranslationKey.skip: "Skip",
    TranslationKey.startNow: "Start Now",
    TranslationKey.next: "Next",
    TranslationKey.welcomeScreenTitle: "Welcome to E-Hub",
    TranslationKey.welcomeScreenText: "Your trusted partner for heavy equipment rental",
    TranslationKey.signInText: "Sign In",
    TranslationKey.signUpText: "Sign Up",
    TranslationKey.guestText: "Browse as Guest",
    TranslationKey.dayKey: "Day",
    TranslationKey.daysKey: "Days",
    TranslationKey.rentalPeriodKey: "Rental Period",
    TranslationKey.startDateKey: "Start Date",
    TranslationKey.endDateKey: "End Date",
    TranslationKey.chooseDateKey: "Tap to change dates",
    TranslationKey.startSearchKey: "Search",
    TranslationKey.chooseLocKey: "Location",
    TranslationKey.endDateTitleKey: "Rental End Date",
    TranslationKey.endDateTextKey: "Select rental end date",
    TranslationKey.endDateButtonKey: "Confirm and complete rental end date",
    TranslationKey.startDateTitleKey: "Confirm rental start date",
    TranslationKey.startDateTextKey: "Select rental start date",
    TranslationKey.startDateButtonKey: "Confirm rental start date",
    TranslationKey.questionTitle1: "Are monthly equipment contracts available?",
    TranslationKey.questionAnswer1: "Yes, daily / weekly / monthly / for a specified period.",
    TranslationKey.questionTitle2: "Does the site cover the Gulf countries and the Kingdom? Equipment / Transportation",
    TranslationKey.questionAnswer2: "Yes, the platform is modern and serves the Gulf countries and the Middle East.",
    TranslationKey.questionTitle3: "Are scaffolding and generator companies registered on the site?",
    TranslationKey.questionAnswer3: "Yes, all transportation, construction needs, and equipment. Workers include qualified engineers, general laborers, and drivers.",
    TranslationKey.questionTitle4: "What is the payment payout duration? Receiving rental payout",
    TranslationKey.questionAnswer4: "Yes, within 3 working days.",
    TranslationKey.questionTitle5: "Can equipment be rented without a driver?",
    TranslationKey.questionAnswer5: "Yes, each contract has its terms based on supply and demand.",
    TranslationKey.searchLocKey: "Search for cities or countries...",
    TranslationKey.drawerTap1: "Sign In",
     TranslationKey.drawerTap8:"profile",
    TranslationKey.drawerTap2: "Home",
    TranslationKey.drawerTap3: "Equipment Catalog",
    TranslationKey.drawerTap4: "Track Order",
    TranslationKey.drawerTap5: "About Us",
    TranslationKey.drawerTap6: "Contact Us",
    TranslationKey.drawerTap7: "AR",
    TranslationKey.searchForEquip:"Search for equipment...",
    TranslationKey.reviewsNo: "reviews",
    TranslationKey.priceSelectionKey: "Price for selected period:",
    TranslationKey.deliverySelectionKey: "Est. Delivery (each way) ",
    TranslationKey.addToCartKey: "ADD TO CART",
    TranslationKey.periodKey1: "Daily",
    TranslationKey.periodKey2: "Weekly",
    TranslationKey.periodKey3: "4 Weeks",
    TranslationKey.seeMoreOptionKey:"See all options",
    TranslationKey.checkDataTapKey1: 'JOBSITE',
    TranslationKey.checkDataTapKey2:  'RENTAL\nDATES',
    TranslationKey.checkDataTapKey3:'ATTACHMENTS\n& REQUESTS',
    TranslationKey.checkDataTapKey4: 'DELIVERY\nPREFERENCES',
    TranslationKey.checkDataTapKey5:'CONTACT\nINFO',
    TranslationKey.checkDataTapKey6:'BILLING',
    TranslationKey.addressTapKey1: "Full name",
   TranslationKey.addressTapKey2: "Company Name",
   TranslationKey.addressTapKey3:  "Country",
   TranslationKey.addressTapKey4: "City",
   TranslationKey.addressTapKey5: "Zip Code",
   TranslationKey.addressTapKey6: "Street Address",
    TranslationKey.timePicker1:  'Morning (7-10 AM)',
    TranslationKey.timePicker2:'Midday (11 AM-2 PM)',
    TranslationKey.timePicker3:'Afternoon (2-5 PM)',
    TranslationKey.timePicker4:'Evening (5-8 PM)',
    TranslationKey.chooseDatesKey:"Select dates",
    TranslationKey.monthsKey:"Months",
    TranslationKey.monthKey:"Month",
    TranslationKey.rentalStartDateKey: "Rental Start Date",
   TranslationKey.rentalEndDateKey: "Rental End Date",
   TranslationKey.rentalStartTimeKey: "Rental Start Time",
   TranslationKey.rentalEndTimeKey: "Rental End Time",
   TranslationKey.attachmentsTitleKey:'Attachments & Requests',
    TranslationKey.attachmentsTextKey:'Need a certain type of bucket? A fork, auger or thumbs?\nAdd a note to the rental company.',
    TranslationKey.addNoteTitleKey:"add note",
    TranslationKey.addNoteTextKey:"Type Your Request Here...",
    TranslationKey.optionalKey:"optional",
    TranslationKey.deliveryTitle1:"Delivery",
   TranslationKey.deliveryTitle2:"Return",
   TranslationKey.deliveryChoice1:"Rental company for delivery – 50 SR",
   TranslationKey.deliveryChoice2:"Customers to pick-up – no delivery fee",
    TranslationKey.anyInstructionText:"Any special instructions...",
    TranslationKey.contactInformationTitle: "Contact Information",
   TranslationKey.contactInformationSubTitle: "Provide the name and address of the renter",
   TranslationKey.contactInformationEmail: "Email",
   TranslationKey.contactInformationMobileNumber: "Mobile number",
   TranslationKey.contactInformationFirstName: "First name",
   TranslationKey. contactInformationLastName: "Last name",
   TranslationKey.contactInformationCompanyName: "Company name",
   TranslationKey.contactInformationOnSiteTitle: "On site contact",
   TranslationKey.contactInformationOnSiteSubTitle: "Same as main contact",
   TranslationKey.contactInformationOnSiteEmail: "On site contact email",
   TranslationKey.contactInformationOnSiteMobileNumber: "On site contact number",
   TranslationKey.contactInformationOnSiteName: "On site contact full name",
    TranslationKey.billingTitles: "Billing Preferences",
   TranslationKey.billingSubTitles: "How would you like to pay for the reservation?",
   TranslationKey.billingFirstWay: "Cash",
   TranslationKey.billingSecondWay: "Card (PayFort)",
   TranslationKey.billingThirdWay: "Credit / Debit Card (Stripe)",
     TranslationKey.emailAlreadyRegistered: "This email is already registered",
     TranslationKey.enterEmail: "Enter email address",
     TranslationKey.invalidEmail: "Invalid email address",
     TranslationKey.enterPassword: "Enter password",
     TranslationKey.passwordMinLength: "Password must be at least 8 characters",
     TranslationKey.passwordNeedsUppercase: "Must contain an uppercase letter",
     TranslationKey.passwordNeedsLowercase: "Must contain a lowercase letter",
     TranslationKey.passwordNeedsNumber: "Must contain at least one number",
     TranslationKey.confirmPassword: "Confirm password",
     TranslationKey.passwordsDoNotMatch: "Passwords do not match",
     TranslationKey.enterName: "Enter name",
     TranslationKey.enterFirstName: "Enter first name",
     TranslationKey.enterLastName: "Enter last name",
     TranslationKey.enterPhone: "Enter phone number",
     TranslationKey.invalidPhone: "Invalid phone number",
     TranslationKey.mustAgreeToTerms: "You must agree to the terms and conditions",
     TranslationKey.enterCity: "Enter city",
     TranslationKey.enterComplaintDepartment: "Enter the complaint department",
     TranslationKey.enterComplaintTitle: "Enter complaint title",
     TranslationKey.enterComplaintText: "Enter complaint text",
     TranslationKey.fieldRequired: "This field is required",
     TranslationKey.postalCodeRequired: "Postal code is required",
     TranslationKey.postalCodeFiveDigits: "Postal code must be exactly 5 digits",
     TranslationKey.postalCodeDigitsOnly: "Postal code must contain digits only",
     TranslationKey.buildingNumberRequired: "Building number is required",
     TranslationKey.buildingNumberFourDigits: "Building number must be exactly 4 digits",
     TranslationKey.buildingNumberDigitsOnly: "Building number must contain digits only",
     TranslationKey.signUpTitle: 'Create Account',
     TranslationKey.signInTitle: 'Sign In',
     TranslationKey.nameFieldTitle: 'Full Name',
     TranslationKey.nameFieldHint: 'John Doe',
     TranslationKey.emailFieldTitle: 'Email Address',
     TranslationKey.emailFieldHint: 'name@company.com',
     TranslationKey.phoneFieldTitle: 'Phone Number',
     TranslationKey.phoneFieldHint: '20 XXX XXX XXXX',
     TranslationKey.passFieldTitle: 'Password',
     TranslationKey.passFieldHint: 'Create password',
     TranslationKey.confirmPassFieldTitle: 'Confirm Password',
     TranslationKey.confirmPassFieldHint: 'Repeat password',
     TranslationKey.haveAnAccount: 'Already have an account?',
     TranslationKey.successfullyRegister:'your email have been successfully registered',
     TranslationKey.checkYourInternet: 'Check your internet connection',
     TranslationKey.tryAgainLater: 'An error occurred. Please try again later',
     TranslationKey.successTitle: 'Success',
     TranslationKey.errorTitle: 'An error occurred', // Or simply 'Error'
     TranslationKey.infoTitle: 'Information',     // Or simply 'Info'
     TranslationKey.warningTitle: 'Warning',
     TranslationKey.wrongCredentials: 'Incorrect email or password',
     TranslationKey.expiredOtp: 'The code has expired. Please resend',
     TranslationKey.wrongOtp: 'Incorrect code. Please try again',
     TranslationKey.successfullyResendOtp: "The verification code has been resent successfully",
     TranslationKey.errorResendOtp: 'Resend failed. Please try again',
     TranslationKey.otpTitle: "Verify Phone Number",
     TranslationKey.otpText: "An OTP code has been sent via WhatsApp to\n",
     TranslationKey.otpButtonTitle:'verify now',
     TranslationKey.otpVerificationSuccessTitle:"have been verified successfully",
     TranslationKey.otpVerificationSuccessText: 'welcome to EHUB...',
     TranslationKey.otpVerificationResendText: "Resending The Code in",
     TranslationKey.secondKey: " Seconds",
     TranslationKey.otpVerificationBTNResendTitle:'resend the code',
     TranslationKey.otpVerificationText: 'we are resending the code...',
     TranslationKey.passSignInFieldTitle: 'Password',
     TranslationKey.passSignInFieldHint: '••••••••••',
     TranslationKey.doNotHaveAnAccount: 'Don\'t have an account?',
     TranslationKey.forgetPass: 'Forgot password?',
     TranslationKey.succeedInOtpVerification: "your email has been verified",
     TranslationKey.succeedInSigningIn: "Welcome to Rosana Resort! An OTP code has been sent to your WhatsApp, please check it.",     TranslationKey.forgotPasswordTitle: 'Forgot Password',
     TranslationKey.forgotPasswordSubtitle: 'Enter your email address below and we will send you an email to reset your password.',
     TranslationKey.forgotPasswordSendCodeButton: 'Send Email',
     TranslationKey.forgotPasswordSuccessMessage: 'We have sent a password reset email to your email address.',
     TranslationKey.logoutDialogTitle: 'Logout',
     TranslationKey.logoutDialogMessage: 'Are you sure you want to log out?',
     TranslationKey.logoutDialogConfirmLabel: 'Logout',
     TranslationKey.deleteAccountDialogTitle: 'Delete Account',
     TranslationKey.deleteAccountDialogMessage: 'Your account and all your data will be permanently deleted. Are you sure?',
     TranslationKey.deleteAccountDialogConfirmLabel: 'Delete Permanently',
     TranslationKey.personalInfoSectionHeader: 'Personal Information',
     TranslationKey.fullNameLabel: 'Full Name',
     TranslationKey.emailLabel: 'Email Address',
     TranslationKey.phoneLabel: 'Phone Number',
     TranslationKey.companySectionHeader: 'Company & Location',
     TranslationKey.addressLabel: 'Address',
     TranslationKey.countryLabel: 'Country',
     TranslationKey.cityLabel: 'City',
     TranslationKey.accountSettingsSectionHeader: 'Account Settings',
     TranslationKey.changePasswordTitle: 'Change Password',
     TranslationKey.changePasswordSubtitle: 'Update security settings',
     TranslationKey.editProfileTitle: 'Edit Profile Details',
     TranslationKey.editProfileSubtitle: 'Update profile',
     TranslationKey.notificationsTitle: 'Notifications',
     TranslationKey.notificationsSubtitle: 'Manage notification preferences',
     TranslationKey.languageTitle: 'Language',
     TranslationKey.languageSubtitle: 'English',
     TranslationKey.languageBadge: 'EN',
     TranslationKey.logoutTileTitle: 'Logout',
     TranslationKey.deleteAccountTileTitle: 'Delete Account',
     TranslationKey.deleteAccountTileSubtitle: 'This action cannot be undone',
     TranslationKey.memberSince: 'Member\nSince',
     TranslationKey.activeRentals: 'Active\nRentals',
     TranslationKey.totalOrders: 'Total\nOrders',
     TranslationKey.editProfileAppBarTitle: 'Edit Profile',
     TranslationKey.saveButtonLabel: 'Save',
     TranslationKey.nameRequiredError: 'Name is required',
     TranslationKey.phoneRequiredError: 'Phone number is required',
     TranslationKey.profileUpdateSuccess: "Profile updated successfully",
     TranslationKey.cancelKey: "Cancel",
     TranslationKey.logoutFailedMsg: "Logout failed. Please try again.",
     TranslationKey.logoutSuccess: "You have been safely logged out. See you soon!",
     TranslationKey.changePasswordPageTitle: "Change Password",
     TranslationKey.changePasswordPageSubtitle: "Enter your current password, then the new one",
     TranslationKey.currentPasswordLabel: "Current Password",
     TranslationKey.currentPasswordHint: "••••••••",
     TranslationKey.newPasswordLabel: "New Password",
     TranslationKey.newPasswordHint: "Create a strong password",
     TranslationKey.confirmPasswordLabel: "Confirm New Password",
     TranslationKey.confirmPasswordHint: "Repeat the password",
     TranslationKey.passwordRequirements: "Password Requirements",
     TranslationKey.ruleMinCharacters: "At least 8 characters",
     TranslationKey.ruleUppercase: "At least one uppercase letter (A-Z)",
     TranslationKey.ruleNumber: "At least one number (0-9)",
     TranslationKey.changePasswordBtn: "Change Password",
     TranslationKey.strengthLabel: "Password Strength",
     TranslationKey.strengthWeak: "Weak",
     TranslationKey.strengthMedium: "Medium",
     TranslationKey.strengthGood: "Good",
     TranslationKey.strengthVeryStrong: "Very Strong",
     TranslationKey.successChangePassTxt: 'Current password has been entered and a secure new password selected. ',
     TranslationKey.currentPasswordIncorrect: 'The current password is incorrect.',
     TranslationKey.passwordMustBeDifferent: 'The new password must be different from your current password.',
     TranslationKey.successfullyRequestForgetPass: 'Your email has been verified successfully. You can now change your password.',
     TranslationKey.passwordResetSuccessfully:"Your password has been successfully reset",
     TranslationKey.faqKey:"Frequently Asked Questions",
     TranslationKey.deleteAccountAuthTitle: 'Confirm Account Deletion',
     TranslationKey.deleteAccountAuthReason: 'Please authenticate to confirm the permanent deletion of your EHUB account. This action cannot be undone.',
     TranslationKey.deleteAccountAuthCancel: 'Cancel',
     TranslationKey.aboutUs: "About us",
     TranslationKey.heroTitlePart1: "The #1 ",
     TranslationKey.heroTitlePart2: "heavy equipment ",
     TranslationKey.heroTitlePart3: "marketplace",
     TranslationKey.heroSubtitle: "Ehub connects contractors with the best registered equipment rental companies across the Gulf.",
     TranslationKey.statsCompanies: "companies",
     TranslationKey.statsMachines: "machines",
     TranslationKey.statsCountries: "GCC countries",
     TranslationKey.ourMission: "Our mission",
     TranslationKey.ourGoal: "Our goal",
     TranslationKey.ourGoalBody: "Simplify heavy equipment rental for hundreds of thousands of contractors through a single trusted digital platform.",
     TranslationKey.ourVision: "Our vision",
     TranslationKey.ourVisionBody: "To be the #1 equipment rental reference in the Middle East by 2030.",
     TranslationKey.whyEhub: "Why Ehub",
     TranslationKey.featOneStopTitle: "One-stop solution",
     TranslationKey.featOneStopBody: "Rentals & logistics in one place",
     TranslationKey.featWideRangeTitle: "Wide range",
     TranslationKey.featWideRangeBody: "Thousands of machines for every job",
     TranslationKey.featDeliveryTitle: "Reliable delivery",
     TranslationKey.featDeliveryBody: "Seamless on-time logistics",
     TranslationKey.featPricingTitle: "Transparent pricing",
     TranslationKey.featPricingBody: "No hidden fees",
     TranslationKey.contactUs: "Contact us",
     TranslationKey.contactLocation: "Riyadh, Saudi Arabia",
     TranslationKey.ctaBannerText: "Start renting equipment\ntoday with Ehub",
     TranslationKey.sortPriceHighToLow: "Price: High to Low",
     TranslationKey.sortPriceLowToHigh: "Price: Low to High",
     TranslationKey.sortNewest: "Newest",
     TranslationKey.sortTopRated: "Top Rated",
     TranslationKey.filterSheetTitle:"Sort By",
     TranslationKey.similarProductsKey:"See all options",
     TranslationKey.hideDetails: "Hide Details",
     TranslationKey.additionalSpecs: "Additional Specifications",
     TranslationKey.noAdditionalSpecs: "No additional specifications available for this product.",
     TranslationKey.availableOffers: "Available Offers",
     TranslationKey.showDetails: "Show Details",
     TranslationKey.requiredNationalId: "National ID is required",
     TranslationKey.invalidNationalId: "Invalid National ID, must be 14 digits",
     TranslationKey.requiredEgyPhone: "Egyptian phone number is required",
     TranslationKey.invalidEgyPhone: "Invalid phone number. Must start with 010, 011, 012, or 015 and be 11 digits",
     TranslationKey.requiredLoginPassword: "Password is required to sign in",
     TranslationKey.vpnAlertTitle: "Important Security Alert",
     TranslationKey.vpnAlertContent: "An active VPN connection has been detected. To protect your account security and verify your real location, you must disable the VPN first; otherwise, you will not be able to log in or complete registration.",
     TranslationKey.vpnRetryButton: "I have turned it off, retry",
     TranslationKey.locationAlertTitle: "Location Permission Required",
     TranslationKey.locationAlertContent: "This application requires access to your location to verify service areas and confirm your authentic location. Please enable location permissions in settings to log in and proceed.",
     TranslationKey.openSettingsButton: "Open Settings",
     TranslationKey.vpnToastError: "Please disable your VPN to proceed",
     TranslationKey.nationalIdFieldTitle: "National ID",
     TranslationKey.nationalIdFieldHint: "Enter 14 digits (e.g. 29001011234567)",
     // Location & Fraud Prevention Security
     TranslationKey.fakeLocationTitle: "تم رصد موقع وهمي",
     TranslationKey.fakeLocationContent: "يرجى إيقاف تفعيل تطبيقات تغيير الموقع (Fake GPS) للمتابعة والتعامل الآمن على المنصة.",
     TranslationKey.retryButton: "إعادة المحاولة",
   };
  }
  else if (locale.languageCode == 'ar') {
   return {
    TranslationKey.onBoardingText1:" تشكيلة واسعة من المعدات الثقيلة والخفيفة لكل أنواع المشاريع",
    TranslationKey.onBoardingText2:"حجز ذكي وتوصيل سريع ومباشر إلى موقع العمل بضغطة زر",
    TranslationKey.onBoardingText3:"معدات مضمونة، صيانة دورية، ودعم فني متكامل لضمان نجاحك",
    TranslationKey.onBoardingTitle1:"معداتك.. في جيبك",
    TranslationKey.onBoardingTitle2:"اطلبها.. توصلك لموقعك",
    TranslationKey.onBoardingTitle3:"ابدأ بناءك.. بثقة",
    TranslationKey.goBack:"الرجوع",
    TranslationKey.skip:"تخطي",
    TranslationKey.startNow:"ابدأ الان",
    TranslationKey.next:"التالي",
    TranslationKey.welcomeScreenTitle:"مرحباً بك في إي هاب",
    TranslationKey.welcomeScreenText:"شريكك الموثوق لتأجير المعدات الثقيلة",
    TranslationKey.signInText:"تسجيل الدخول",
    TranslationKey.signUpText:"إنشاء حساب جديد",
    TranslationKey.guestText:"تصفح كزائر",
    TranslationKey.dayKey:"يوم",
    TranslationKey.daysKey:"أيام",
    TranslationKey.rentalPeriodKey:"مدة الإيجار",
    TranslationKey.startDateKey:"تاريخ البداية",
    TranslationKey.endDateKey:" 'تاريخ النهاية'",
    TranslationKey.chooseDateKey:"اضغط لتغيير التواريخ",
    TranslationKey.startSearchKey:"بحث",
    TranslationKey.chooseLocKey:"العنوان",
    TranslationKey.endDateTitleKey:"تاريخ نهاية الإيجار",
    TranslationKey.endDateTextKey:"اختر يوم انتهاء الاستئجار",
    TranslationKey.endDateButtonKey:"تأكيد وإتمام تاريخ نهاية الإيجار",
    TranslationKey.startDateTitleKey:'تأكيد تاريخ بداية الإيجار',
    TranslationKey.startDateTextKey: 'اختر يوم بداية الاستئجار',
    TranslationKey.startDateButtonKey:'تأكيد تاريخ بداية الإيجار',
    TranslationKey.questionTitle1:"هل تتوفر عقود شهرية للمعدات؟",
    TranslationKey.questionAnswer1:"نعم، يومي / أسبوعي / شهري / لفترة محددة.",
    TranslationKey.questionTitle2:"'هل الموقع يشمل دول الخليج والمملكة؟ المعدات / النقل",
    TranslationKey.questionAnswer2:"نعم، الموقع حديث وهو لدول الخليج والشرق الأوسط.",
    TranslationKey.questionTitle3:"هل شركات السقالات والمولدات مشتركة في الموقع؟",
    TranslationKey.questionAnswer3:"نعم، جميع احتياجات النقل والبناء وجميع المعدات. العمال مهندسون مؤهلون وعمال عاديون وسائقون.",
    TranslationKey.questionTitle4:"ما هي المدة التي يتم فيها السداد؟ استلام الإيجار",
    TranslationKey.questionAnswer4:"نعم، خلال 3 أيام عمل.",
    TranslationKey.questionTitle5:"هل يمكن استئجار المعدات بدون سائق؟",
    TranslationKey.questionAnswer5:"نعم، كل عقد له شروطه وفقاً للعرض والطلب.",
    TranslationKey.searchLocKey:"ابحث عن المدن أو البلدان...",
    TranslationKey.drawerTap1:"تسجيل الدخول",
    TranslationKey.drawerTap2:"الرئيسية",
    TranslationKey.drawerTap3:"كتالوج المعدات",
    TranslationKey.drawerTap4:"تتبع الطلب",
    TranslationKey.drawerTap5:"من نحن",
    TranslationKey.drawerTap6:"اتصل بنا",
    TranslationKey.searchForEquip:"ابحث عن المعدات...",
    TranslationKey.drawerTap7:"EN",
    TranslationKey.filterSheetTitle:"ترتيب حسب",
  TranslationKey.reviewsNo: "تقييمات", // أو "تقييم" حسب طريقة عرض الرقم قبلها
  TranslationKey.priceSelectionKey: "السعر للمدة المحددة:",
  TranslationKey.deliverySelectionKey: "تكلفة التوصيل التقديرية (لكل اتجاه)",
  TranslationKey.addToCartKey: "إضافة إلى السلة",
  TranslationKey.periodKey1: "يومي",
  TranslationKey.periodKey2: "أسبوعي",
  TranslationKey.periodKey3: "٤ أسابيع", // أو "شهري" إذا كان هذا هو المقصود بها في نظامك
  TranslationKey.seeMoreOptionKey: "عرض جميع الخيارات",
    TranslationKey.checkDataTapKey1: 'موقع العمل',
    TranslationKey.checkDataTapKey2: 'تواريخ\nالإيجار',
    TranslationKey.checkDataTapKey3: 'المرفقات\nوالطلبات',
    TranslationKey.checkDataTapKey4: 'تفضيلات\nالتسليم',
    TranslationKey.checkDataTapKey5: 'معلومات\nالتواصل',
    TranslationKey.checkDataTapKey6: 'الفواتير',
    TranslationKey.addressTapKey1: "الاسم الكامل",
    TranslationKey.addressTapKey2: "اسم الشركة",
    TranslationKey.addressTapKey3: "الدولة",
    TranslationKey.addressTapKey4: "المدينة",
    TranslationKey.addressTapKey5: "الرمز البريدي",
    TranslationKey.addressTapKey6: "عنوان الشارع",
    TranslationKey.timePicker1: 'الصباح (7-10 ص)',
    TranslationKey.timePicker2: 'منتصف اليوم (11 ص - 2 م)',
    TranslationKey.timePicker3: 'بعد الظهر (2-5 م)',
    TranslationKey.timePicker4: 'المساء (5-8 م)',
    TranslationKey.chooseDatesKey: "اختر التواريخ",
    TranslationKey.monthsKey: "الأشهر",
    TranslationKey.monthKey: "شهر",
    TranslationKey.rentalStartDateKey: "تاريخ بدء الإيجار",
    TranslationKey.rentalEndDateKey: "تاريخ انتهاء الإيجار",
    TranslationKey.rentalStartTimeKey: "وقت بدء الإيجار",
    TranslationKey.rentalEndTimeKey: "وقت انتهاء الإيجار",
    TranslationKey.attachmentsTitleKey: 'المرفقات والطلبات',
    TranslationKey.attachmentsTextKey:
    'هل تحتاج إلى نوع معين من الدلاء؟ شوكة، مثقاب أو أذرع تثبيت؟\nأضف ملاحظة إلى شركة التأجير.',
    TranslationKey.addNoteTitleKey: "إضافة ملاحظة",
    TranslationKey.addNoteTextKey: "اكتب طلبك هنا...",
    TranslationKey.optionalKey: "اختياري",
    TranslationKey.deliveryTitle1: "التوصيل",
    TranslationKey.deliveryTitle2: "الاسترجاع",
    TranslationKey.deliveryChoice1: "شركة التأجير للتوصيل – 50 ريال",
    TranslationKey.deliveryChoice2: "استلام العميل بنفسه – بدون رسوم توصيل",
    TranslationKey.anyInstructionText: "أي تعليمات خاصة...",
    TranslationKey.anyInstructionText: "أي تعليمات خاصة...",
    TranslationKey.contactInformationTitle: "معلومات التواصل",
    TranslationKey.contactInformationSubTitle: "قم بتوفير اسم وعنوان المستأجر",
    TranslationKey.contactInformationEmail: "البريد الإلكتروني",
    TranslationKey.contactInformationMobileNumber: "رقم الجوال",
    TranslationKey.contactInformationFirstName: "الاسم الأول",
    TranslationKey.contactInformationLastName: "اسم العائلة",
    TranslationKey.contactInformationCompanyName: "اسم الشركة",
    TranslationKey.contactInformationOnSiteTitle: "جهة الاتصال في الموقع",
    TranslationKey.contactInformationOnSiteSubTitle: "نفس جهة الاتصال الرئيسية",
    TranslationKey.contactInformationOnSiteEmail: "البريد الإلكتروني لجهة الاتصال في الموقع",
    TranslationKey.contactInformationOnSiteMobileNumber: "رقم جهة الاتصال في الموقع",
    TranslationKey.contactInformationOnSiteName: "الاسم الكامل لجهة الاتصال في الموقع",
    TranslationKey.billingTitles: "خيارات الدفع",
    TranslationKey.billingSubTitles: "كيف تود الدفع مقابل الحجز؟",
    TranslationKey.billingFirstWay: "نقدًا",
    TranslationKey.billingSecondWay: "بطاقة (PayFort)",
    TranslationKey.billingThirdWay: "بطاقة ائتمان / خصم مباشر (Stripe)",
     TranslationKey.emailAlreadyRegistered: "هذا البريد الإلكتروني مسجل مسبقاً",
     TranslationKey.enterEmail: "أدخل البريد الإلكتروني",
     TranslationKey.invalidEmail: "بريد إلكتروني غير صالح",
     TranslationKey.enterPassword: "أدخل كلمة المرور",
     TranslationKey.passwordMinLength: "كلمة المرور يجب أن تكون 8 أحرف على الأقل",
     TranslationKey.passwordNeedsUppercase: "يجب أن تحتوي على حرف كبير",
     TranslationKey.passwordNeedsLowercase: "يجب أن تحتوي على حرف صغير",
     TranslationKey.passwordNeedsNumber: "يجب أن تحتوي على رقم واحد على الأقل",
     TranslationKey.confirmPassword: "أكد كلمة المرور",
     TranslationKey.passwordsDoNotMatch: "كلمة المرور غير متطابقة",
     TranslationKey.enterName: "أدخل الاسم",
     TranslationKey.enterFirstName: "أدخل الاسم الأول",
     TranslationKey.enterLastName: "أدخل الاسم الأخير",
     TranslationKey.enterPhone: "أدخل رقم الهاتف",
     TranslationKey.invalidPhone: "رقم الهاتف غير صالح",
     TranslationKey.mustAgreeToTerms: "يجب الموافقة على الشروط والأحكام",
     TranslationKey.enterCity: "أدخل المدينة",
     TranslationKey.enterComplaintDepartment: "أدخل القسم الموجه له الشكوى",
     TranslationKey.enterComplaintTitle: "أدخل عنوان الشكوى",
     TranslationKey.enterComplaintText: "أدخل نص الشكوى",
     TranslationKey.fieldRequired: "هذا الحقل مطلوب",
     TranslationKey.postalCodeRequired: "الرمز البريدي مطلوب",
     TranslationKey.postalCodeFiveDigits: "يجب أن يتكون الرمز البريدي من 5 أرقام بالضبط",
     TranslationKey.postalCodeDigitsOnly: "الرمز البريدي يجب أن يحتوي على أرقام فقط",
     TranslationKey.buildingNumberRequired: "رقم المبنى مطلوب",
     TranslationKey.buildingNumberFourDigits: "يجب أن يتكون رقم المبنى من 4 أرقام بالضبط",
     TranslationKey.buildingNumberDigitsOnly: "رقم المبنى يجب أن يحتوي على أرقام فقط",
     TranslationKey.signUpTitle:'إنشاء حساب',
   TranslationKey.signInTitle:'تسجيل الدخول',
   TranslationKey.nameFieldTitle:  'الاسم الكامل',
   TranslationKey.nameFieldHint: 'جون دو',
   TranslationKey.emailFieldTitle:  'البريد الإلكتروني',
   TranslationKey.emailFieldHint: 'name@company.com',
   TranslationKey.phoneFieldTitle: 'رقم الهاتف',
   TranslationKey.phoneFieldHint:'20 XXX XXX XXXX',
     TranslationKey.nationalIdFieldTitle: "National ID",
     TranslationKey.nationalIdFieldHint: "Enter 14 digits (e.g. 29001011234567)",
   TranslationKey.passFieldTitle: 'كلمة المرور',
   TranslationKey.passFieldHint: 'إنشاء كلمة المرور',
   TranslationKey.confirmPassFieldTitle:'تأكيد كلمة المرور',
   TranslationKey.confirmPassFieldHint: 'كرر كلمة المرور',
   TranslationKey.haveAnAccount:'لديك حساب؟',
     TranslationKey.passSignInFieldTitle: 'كلمة المرور',
   TranslationKey.passSignInFieldHint: '••••••••••',
   TranslationKey.doNotHaveAnAccount: 'ليس لديك حساب؟',
   TranslationKey.forgetPass:'نسيت كلمة المرور؟',
     TranslationKey.successfullyRegister: 'تم التسجيل بنجاح',
     TranslationKey.successfullyRequestForgetPass:"تم التحقق من بريدك الإلكتروني بنجاح يمكنك الإن تغير كلمه السر ",
     TranslationKey.checkYourInternet:"تحقق من اتصالك بالإنترنت",
     TranslationKey.tryAgainLater:"حدث خطأ. يرجى المحاولة مرة أخرى",
     TranslationKey.successTitle: "تم بنجاح",
   TranslationKey.errorTitle: "حدث خطأ",
   TranslationKey.infoTitle: "تنبيه",
   TranslationKey.warningTitle: "معلومة",
     TranslationKey.wrongCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
     TranslationKey.expiredOtp: 'انتهت صلاحية الرمز. أعد الإرسال',
     TranslationKey.wrongOtp:'الرمز غير صحيح. يرجى المحاولة مرة أخرى',
     TranslationKey.successfullyResendOtp: 'تم إعادة إرسال رمز التحقق بنجاح',
     TranslationKey.errorResendOtp:"فشل إعادة الإرسال. حاول مجددا",

        TranslationKey.otpTitle: "تأكيد رقم الهاتف",
       TranslationKey.otpText: "تم إرسال رمز التحقق عبر واتساب إلى\n",

   TranslationKey.otpButtonTitle:'تحقق الآن',
   TranslationKey.otpVerificationSuccessTitle:" تم التحقق بنجاح!",
   TranslationKey.otpVerificationSuccessText: 'جاري الانتقال...',
     TranslationKey.otpVerificationResendText: "إعادة الإرسال خلال ",
   TranslationKey.secondKey: " ثانية",
     TranslationKey.otpVerificationBTNResendTitle:'إعادة إرسال الرمز',
     TranslationKey.otpVerificationText: 'جاري إعادة الإرسال...',
     TranslationKey.succeedInOtpVerification: 'تم التحقق من بريدك الإلكتروني بنجاح',
     TranslationKey.succeedInSigningIn: "مرحباً بك في منتجع روزانا! تم إرسال رمز التحقق (OTP) إلى رقمك على واتساب، يرجى التحقق منه.",
     TranslationKey.drawerTap8: 'الملف الشخصي',
     TranslationKey.forgotPasswordTitle: 'نسيت كلمة المرور',
     TranslationKey.forgotPasswordSubtitle: 'يرجى إدخال بريدك الإلكتروني. سنقوم بإرسال رمز تحقق (OTP) إلى هذا البريد للتأكد من هويتك قبل إتمام عملية التغيير.',
     TranslationKey.forgotPasswordSendCodeButton: 'إرسال رمز التحقق',
     TranslationKey.forgotPasswordSuccessMessage: 'لقد أرسلنا بريداً لإعادة تعيين كلمة المرور إلى بريدك الإلكتروني.',
     TranslationKey.personalInfoSectionHeader: 'المعلومات الشخصية', // 'Personal Information'
     TranslationKey.fullNameLabel: 'الاسم الكامل', // 'Full Name'
     TranslationKey.emailLabel: 'البريد الإلكتروني', // 'Email Address'
     TranslationKey.phoneLabel: 'رقم الهاتف', // 'Phone Number'
     TranslationKey.logoutDialogTitle: 'تسجيل الخروج', // 'Logout'
     TranslationKey.logoutDialogMessage: 'هل أنت متأكد أنك تريد تسجيل الخروج؟', // 'Are you sure you want to log out?'
     TranslationKey.logoutDialogConfirmLabel: 'خروج', // 'Logout'
     TranslationKey.deleteAccountDialogTitle: 'حذف الحساب', // 'Delete Account'
     TranslationKey.deleteAccountDialogMessage: 'سيتم حذف حسابك وجميع بياناتك بشكل نهائي. هل أنت متأكد؟', // 'Your account and all your data will be permanently deleted. Are you sure?'
     TranslationKey.deleteAccountDialogConfirmLabel: 'حذف نهائي',
     TranslationKey.companySectionHeader: 'الشركة والموقع', // 'Company & Location'
     TranslationKey.addressLabel: 'عنوان', // 'Company Name'
     TranslationKey.countryLabel: 'الدولة', // 'Country'
     TranslationKey.cityLabel: 'المدينة',
     TranslationKey.accountSettingsSectionHeader: 'إعدادات الحساب', // 'Account Settings'
     TranslationKey.changePasswordTitle: 'تغيير كلمة المرور', // 'Change Password'
     TranslationKey.changePasswordSubtitle: 'تحديث بيانات الأمان', // 'Update security settings'
     TranslationKey.editProfileTitle: 'تعديل بيانات الملف الشخصي', // 'Edit Profile Details'
     TranslationKey.editProfileSubtitle: 'تحديث الملف الشخصي', // 'Update profile'
     TranslationKey.notificationsTitle: 'الإشعارات', // 'Notifications'
     TranslationKey.notificationsSubtitle: 'إدارة تفضيلات الإشعارات', // 'Manage notification preferences'
     TranslationKey.languageTitle: 'اللغة', // 'Language'
     TranslationKey.languageSubtitle: 'العربية', // 'Arabic'
     TranslationKey.languageBadge: 'AR', // 'EN' (or keep 'AR' if showing current language badge)
     TranslationKey.logoutTileTitle: 'تسجيل الخروج', // 'Logout'
     TranslationKey.deleteAccountTileTitle: 'حذف الحساب', // 'Delete Account'
     TranslationKey.deleteAccountTileSubtitle: 'إجراء لا يمكن التراجع عنه', // 'This action cannot be undone'
     TranslationKey.memberSince: 'عضو\nمنذ',
     TranslationKey.activeRentals: 'إيجارات\nنشطة',
     TranslationKey.totalOrders: 'إجمالي\nالطلبات',
     TranslationKey.editProfileAppBarTitle: 'تعديل الملف الشخصي',
     TranslationKey.saveButtonLabel: 'حفظ',
     TranslationKey.nameRequiredError: 'الاسم مطلوب',
     TranslationKey.phoneRequiredError: 'رقم الهاتف مطلوب',
     TranslationKey.profileUpdateSuccess: "تم تحديث الملف الشخصي بنجاح",
     TranslationKey.cancelKey: "إلغاء",
     TranslationKey.logoutFailedMsg: "فشل تسجيل الخروج. يرجى المحاولة مرة أخرى.",
     TranslationKey.logoutSuccess:"تم تسجيل الخروج بأمان. نراك قريباً!",
     TranslationKey.changePasswordPageTitle: "تغيير كلمة المرور",
     TranslationKey.changePasswordPageSubtitle: "أدخل كلمة المرور الحالية ثم الجديدة",
     TranslationKey.currentPasswordLabel: "كلمة المرور الحالية",
     TranslationKey.currentPasswordHint: "••••••••",
     TranslationKey.newPasswordLabel: "كلمة المرور الجديدة",
     TranslationKey.newPasswordHint: "أنشئ كلمة مرور قوية",
     TranslationKey.confirmPasswordLabel: "تأكيد كلمة المرور الجديدة",
     TranslationKey.confirmPasswordHint: "كرر كلمة المرور",
     TranslationKey.passwordRequirements: "متطلبات كلمة المرور",
     TranslationKey.ruleMinCharacters: "أحرف على الأقل 8",
     TranslationKey.ruleUppercase: "حرف كبير واحد على الأقل (A-Z)",
      TranslationKey.ruleNumber: "رقم واحد على الأقل (0-9)",
     TranslationKey.changePasswordBtn: "تغيير كلمة المرور",
     TranslationKey.strengthLabel: "قوة كلمة المرور",
     TranslationKey.strengthWeak: "ضعيفة",
     TranslationKey.strengthMedium: "متوسطة",
     TranslationKey.strengthGood: "جيدة",
      TranslationKey.strengthVeryStrong: "قوية جداً",
     TranslationKey.successChangePassTxt: 'تم أدخل كلمة المرور الحالية واختيار كلمة مرور جديدة آمنة',
     TranslationKey.currentPasswordIncorrect: 'كلمة المرور الحالية غير صحيحة',
     TranslationKey.passwordMustBeDifferent: 'يجب أن تكون كلمة المرور الجديدة مختلفة عن كلمة المرور الحالية.',
     TranslationKey.passwordResetSuccessfully: 'تمت إعادة تعيين كلمة مرورك بنجاح.',
     TranslationKey.faqKey:"الاسئله الشائعه",
     TranslationKey.deleteAccountAuthTitle: 'تأكيد حذف الحساب',
     TranslationKey.deleteAccountAuthReason: 'يرجى تأكيد هويتك للمتابعة في حذف حسابك في أي-هب نهائياً. لا يمكن التراجع عن هذا الإجراء لاحقاً.',
     TranslationKey.deleteAccountAuthCancel: 'إلغاء',
     TranslationKey.aboutUs: "من نحن",
     TranslationKey.heroTitlePart1: "سوق ",
     TranslationKey.heroTitlePart2: "المعدات الثقيلة ",
     TranslationKey.heroTitlePart3: "الأول",
     TranslationKey.heroSubtitle: "إيهاب يربط المقاولين بأفضل شركات تأجير المعدات المعتمدة في المملكة والخليج",
     TranslationKey.statsCompanies: "شركة مسجلة",
     TranslationKey.statsMachines: "معدة متاحة",
     TranslationKey.statsCountries: "دول خليجية",
     TranslationKey.ourMission: "رسالتنا",
     TranslationKey.ourGoal: "هدفنا",
     TranslationKey.ourGoalBody: "تبسيط عملية تأجير المعدات الثقيلة لمئات الآلاف من المقاولين من خلال منصة رقمية واحدة موثوقة",
     TranslationKey.ourVision: "رؤيتنا",
     TranslationKey.ourVisionBody: "أن نكون المرجع الأول لتأجير المعدات في منطقة الشرق الأوسط بحلول عام 2030",
     TranslationKey.whyEhub: "مميزاتنا",
     TranslationKey.featOneStopTitle: "حل متكامل",
     TranslationKey.featOneStopBody: "إيجار ولوجستيات من مكان واحد",
     TranslationKey.featWideRangeTitle: "تشكيلة واسعة",
     TranslationKey.featWideRangeBody: "آلاف المعدات لجميع المشاريع",
     TranslationKey.featDeliveryTitle: "توصيل موثوق",
     TranslationKey.featDeliveryBody: "خدمة لوجستية سلسة وفي الوقت المحدد",
     TranslationKey.featPricingTitle: "أسعار شفافة",
     TranslationKey.featPricingBody: "بدون رسوم خفية",
     TranslationKey.contactUs: "تواصل معنا",
     TranslationKey.contactLocation: "الرياض — المملكة العربية السعودية",
     TranslationKey.ctaBannerText: "ابدأ تأجير معداتك\nاليوم مع إيهاب",
     TranslationKey.sortPriceHighToLow: "السعر: من الأعلى للأدنى",
     TranslationKey.sortPriceLowToHigh: "السعر: من الأدنى للأعلى",
     TranslationKey.sortNewest: "الأحدث",
     TranslationKey.sortTopRated: "الأعلى تقييماً",
     TranslationKey.similarProductsKey:"عرض كل الخيارات",
     TranslationKey.hideDetails: "إخفاء التفاصيل",
     TranslationKey.additionalSpecs: "مواصفات إضافية",
     TranslationKey.noAdditionalSpecs: "لا توجد مواصفات إضافية متاحة لهذا المنتج.",
     TranslationKey.availableOffers: "عروض متاحة",
     TranslationKey.showDetails: "عرض التفاصيل",
     TranslationKey.requiredNationalId: "الرقم القومي مطلوب",
     TranslationKey.invalidNationalId: "الرقم القومي غير صحيح، يجب أن يتكون من 14 رقماً",
     TranslationKey.requiredEgyPhone: "رقم الهاتف المصري مطلوب",
     TranslationKey.invalidEgyPhone: "رقم هاتف غير صحيح، يجب أن يبدأ بـ 010 أو 011 أو 012 أو 015 ويتكون من 11 رقماً",
     TranslationKey.requiredLoginPassword: "كلمة المرور مطلوبة تسجيل الدخول",
     TranslationKey.vpnAlertTitle: "تنبيه أمني مهم",
     TranslationKey.vpnAlertContent: "لقد تم اكتشاف اتصال شبكة افتراضية (VPN) نشط. لحماية أمن حسابك والتحقق من موقعك الحقيقي، يجب عليك إغلاق الـ VPN أولاً؛ وإلا لن تتمكن من تسجيل الدخول أو إكمال عملية التسجيل.",
     TranslationKey.vpnRetryButton: "لقد قمت بإغلاقه، أعد المحاولة",
     TranslationKey.locationAlertTitle: "صلاحية الموقع مطلوبة",
     TranslationKey.locationAlertContent: "يتطلب هذا التطبيق الوصول إلى موقعك الجغرافي للتحقق من نطاق الخدمة وتأكيد موقعك الحقيقي. يرجى تفعيل الموقع من الإعدادات لتتمكن من تسجيل الدخول وإكمال العملية.",
     TranslationKey.openSettingsButton: "افتح الإعدادات",
     TranslationKey.vpnToastError: "يرجى إيقاف تشغيل الـ VPN للمتابعة",
     // Location & Fraud Prevention Security

     TranslationKey.fakeLocationTitle: "تم رصد موقع وهمي",
     TranslationKey.fakeLocationContent: "يرجى إيقاف تفعيل تطبيقات تغيير الموقع (Fake GPS) للمتابعة والتعامل الآمن على المنصة.",
     TranslationKey.retryButton: "إعادة المحاولة",
   };
  }

  return {};
 }
}